@extends('layouts.app')

@section('content')
@php
    $studentProfile = optional($registration)->studentProfile;
    $documents = optional($registration)->documents ?? collect();
    $profileFields = ['full_name', 'nik', 'gender', 'birth_place', 'birth_date', 'parent_name', 'parent_phone', 'parent_job', 'address'];
    $completedProfile = collect($profileFields)->filter(fn ($field) => filled(optional($studentProfile)->{$field}))->count();
    $completedDocuments = $documents->unique('file_type')->count();
    $isProfileComplete = $completedProfile === count($profileFields) && filled(optional($registration)->unit);
    $progress = (int) round((($isProfileComplete ? 2 : 1) + min(1, $completedDocuments / 4) + (optional($registration)->status && optional($registration)->status !== 'draft' ? 1 : 0) + (in_array(optional($registration)->status, ['passed', 'rejected', 'failed', 'verified']) ? 1 : 0)) / 5 * 100);
    $status = optional($registration)->status ?? 'draft';
    $statusMeta = [
        'draft' => ['label' => 'Belum Lengkap', 'description' => 'Lengkapi biodata dan dokumen untuk memulai proses verifikasi.', 'tone' => 'slate'],
        'pending' => ['label' => 'Menunggu Verifikasi', 'description' => 'Data dan dokumen Anda sedang menunggu pemeriksaan panitia.', 'tone' => 'amber'],
        'verified' => ['label' => 'Terverifikasi', 'description' => 'Data dan dokumen Anda telah diverifikasi oleh panitia.', 'tone' => 'emerald'],
        'passed' => ['label' => 'Diterima', 'description' => 'Selamat, Anda diterima pada proses PPDB ini.', 'tone' => 'blue'],
        'rejected' => ['label' => 'Ditolak', 'description' => 'Pendaftaran Anda belum dapat diterima. Silakan cek catatan dari panitia.', 'tone' => 'rose'],
        'failed' => ['label' => 'Ditolak', 'description' => 'Pendaftaran Anda belum dapat diterima. Silakan cek catatan dari panitia.', 'tone' => 'rose'],
    ];
    $meta = $statusMeta[$status] ?? $statusMeta['draft'];
    $toneClasses = ['slate' => 'border-slate-200 bg-slate-50 text-slate-700', 'amber' => 'border-amber-200 bg-amber-50 text-amber-900', 'emerald' => 'border-emerald-200 bg-emerald-50 text-emerald-900', 'blue' => 'border-blue-200 bg-blue-50 text-blue-900', 'rose' => 'border-rose-200 bg-rose-50 text-rose-900'];
    $documentLabels = ['akta' => 'Akta Kelahiran', 'kk' => 'Kartu Keluarga', 'ijazah_rapor' => 'Ijazah / Rapor', 'pasfoto' => 'Pasfoto'];
    $timeline = [
        ['label' => 'Pendaftaran dibuat', 'done' => filled(optional($registration)->id), 'date' => optional($registration)->created_at?->format('d M Y')],
        ['label' => 'Biodata lengkap', 'done' => $isProfileComplete, 'date' => $isProfileComplete ? optional($studentProfile)->updated_at?->format('d M Y') : null],
        ['label' => 'Dokumen diupload', 'done' => $completedDocuments > 0, 'date' => $completedDocuments > 0 ? $documents->max('created_at')?->format('d M Y') : null],
        ['label' => 'Verifikasi panitia', 'done' => in_array($status, ['verified', 'passed', 'rejected', 'failed']), 'current' => $status === 'pending', 'date' => in_array($status, ['verified', 'passed', 'rejected', 'failed']) ? optional($registration)->updated_at?->format('d M Y') : null],
        ['label' => 'Keputusan', 'done' => in_array($status, ['passed', 'rejected', 'failed']), 'date' => in_array($status, ['passed', 'rejected', 'failed']) ? optional($registration)->updated_at?->format('d M Y') : null],
        ['label' => 'Selesai', 'done' => in_array($status, ['passed', 'rejected', 'failed']), 'date' => in_array($status, ['passed', 'rejected', 'failed']) ? optional($registration)->updated_at?->format('d M Y') : null],
    ];
@endphp

<div x-data="{ uploading: false }" class="page-shell mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <section class="mb-6 rounded-3xl bg-primary p-6 text-white shadow-lg shadow-primary/10 sm:p-8">
        <div class="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between">
            <div><p class="text-sm font-semibold text-blue-100">Dashboard Pendaftar</p><h1 class="mt-2 text-3xl font-bold tracking-tight">Halo, {{ auth()->user()->name }}</h1><p class="mt-2 max-w-xl text-sm leading-6 text-blue-100">Lengkapi data dan dokumen untuk menyelesaikan proses pendaftaran PPDB.</p></div>
            <div class="rounded-2xl border border-white/15 bg-white/10 p-5 lg:min-w-72"><div class="flex items-center justify-between text-sm"><span class="font-semibold">Progress pendaftaran</span><strong>{{ $progress }}%</strong></div><div class="mt-3 h-2 overflow-hidden rounded-full bg-white/20"><div class="h-full rounded-full bg-amber-400 transition-all" style="width: {{ $progress }}%"></div></div><p class="mt-2 text-xs text-blue-100">{{ $completedProfile }}/{{ count($profileFields) }} data biodata Â· {{ $completedDocuments }}/4 dokumen</p></div>
        </div>
        <div class="mt-8 grid grid-cols-5 gap-2 sm:gap-4">
            @foreach([['Akun', true], ['Biodata', $isProfileComplete], ['Dokumen', $completedDocuments === 4], ['Verifikasi', in_array($status, ['verified', 'passed', 'rejected', 'failed'])], ['Hasil', in_array($status, ['passed', 'rejected', 'failed'])]] as $index => $step)
                <div class="relative text-center"><div class="mx-auto flex h-8 w-8 items-center justify-center rounded-full text-xs font-bold {{ $step[1] ? 'bg-amber-400 text-slate-950' : 'border border-white/40 bg-white/10 text-white' }}">{{ $step[1] ? 'âœ“' : $index + 1 }}</div><p class="mt-2 text-[10px] font-semibold text-blue-100 sm:text-xs">{{ $step[0] }}</p>@if($index < 4)<div class="absolute left-[calc(50%+22px)] right-[calc(-50%+22px)] top-4 h-px bg-white/20"></div>@endif</div>
            @endforeach
        </div>
    </section>

    <section class="mb-6 rounded-2xl border p-5 {{ $toneClasses[$meta['tone']] }} sm:p-6">
        <div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div class="flex gap-3"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-white/70 text-lg">{{ $status === 'passed' ? 'âœ“' : ($status === 'rejected' || $status === 'failed' ? '!' : 'â€¢') }}</span><div><p class="text-xs font-bold uppercase tracking-wide opacity-70">Status Anda</p><h2 class="mt-1 text-xl font-bold">{{ $meta['label'] }}</h2><p class="mt-1 text-sm opacity-80">{{ $meta['description'] }}</p>@if(in_array($status, ['rejected', 'failed']))<p class="mt-3 rounded-lg bg-white/60 p-3 text-xs font-semibold">Alasan atau catatan penolakan akan ditampilkan di sini jika diberikan oleh panitia.</p>@endif</div></div>@if($status === 'rejected' || $status === 'failed')<a href="#biodata" class="rounded-xl bg-white px-4 py-2 text-center text-sm font-bold text-rose-700 shadow-sm hover:bg-rose-50">Perbaiki Data</a>@endif</div>
    </section>

    <div class="mb-6 grid gap-3 sm:grid-cols-3"><div class="card p-4"><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">Nomor registrasi</p><p class="mt-2 font-mono text-sm font-bold text-primary">{{ optional($registration)->registration_number ?? 'Belum ada' }}</p></div><div class="card p-4"><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">Unit pendidikan</p><p class="mt-2 font-bold text-slate-800">{{ optional($registration)->unit ?? 'Belum dipilih' }}</p></div><div class="card p-4"><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">Berkas terunggah</p><p class="mt-2 font-bold text-slate-800">{{ $completedDocuments }} dari 4 dokumen</p></div></div>

    <div class="grid items-start gap-6 xl:grid-cols-[1.1fr_0.9fr]">
        <section id="biodata" class="card p-5 sm:p-7">
            <div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p class="eyebrow">Tahap 2 dari 5</p><h2 class="mt-1 text-2xl font-bold text-text-navy">Formulir Biodata</h2><p class="mt-2 text-sm text-slate-500">Isi data dengan dokumen resmi. Kolom bertanda <span class="font-bold text-rose-500">*</span> wajib diisi.</p></div><span class="rounded-full bg-primary/5 px-3 py-1.5 text-xs font-bold text-primary">{{ $completedProfile }}/{{ count($profileFields) }} lengkap</span></div>
            @if($errors->any())<div class="mt-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800"><p class="font-bold">Periksa kembali data Anda:</p><ul class="mt-2 list-disc space-y-1 pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
            <form action="{{ route('student.profile.store') }}" method="POST" class="mt-6 space-y-6">
                @csrf
                <fieldset class="rounded-2xl border border-slate-200 p-4 sm:p-5"><legend class="px-2 text-sm font-bold text-text-navy">A. Data Pendidikan</legend><label class="mt-2 block text-sm font-semibold text-slate-700">Unit Pendidikan <span class="text-rose-500">*</span></label><select name="unit" required class="input-control mt-2 @error('unit') border-rose-400 @enderror"><option value="">Pilih jenjang</option>@foreach(['TK','SD','SMP'] as $unitOption)<option value="{{ $unitOption }}" @selected(old('unit', optional($registration)->unit) === $unitOption)>{{ $unitOption }}</option>@endforeach</select>@error('unit')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</fieldset>
                <fieldset class="rounded-2xl border border-slate-200 p-4 sm:p-5"><legend class="px-2 text-sm font-bold text-text-navy">B. Data Pribadi</legend><div class="grid gap-4 sm:grid-cols-2"><div class="sm:col-span-2"><label class="text-sm font-semibold text-slate-700">Nama Lengkap <span class="text-rose-500">*</span></label><input name="full_name" value="{{ old('full_name', optional($studentProfile)->full_name) }}" required placeholder="Nama sesuai akta kelahiran" class="input-control mt-2 @error('full_name') border-rose-400 @enderror">@error('full_name')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div><div><label class="text-sm font-semibold text-slate-700">NIK <span class="text-rose-500">*</span></label><input name="nik" value="{{ old('nik', optional($studentProfile)->nik) }}" required maxlength="16" minlength="16" inputmode="numeric" pattern="[0-9]{16}" placeholder="16 digit NIK" class="input-control mt-2 @error('nik') border-rose-400 @enderror"><p class="mt-1 text-xs text-slate-400">Masukkan tepat 16 digit angka.</p>@error('nik')<p class="text-xs text-rose-600">{{ $message }}</p>@enderror</div><div><label class="text-sm font-semibold text-slate-700">Jenis Kelamin <span class="text-rose-500">*</span></label><select name="gender" required class="input-control mt-2 @error('gender') border-rose-400 @enderror"><option value="">Pilih jenis kelamin</option><option value="L" @selected(old('gender', optional($studentProfile)->gender) === 'L')>Laki-laki</option><option value="P" @selected(old('gender', optional($studentProfile)->gender) === 'P')>Perempuan</option></select>@error('gender')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div><div><label class="text-sm font-semibold text-slate-700">Tempat Lahir <span class="text-rose-500">*</span></label><input name="birth_place" value="{{ old('birth_place', optional($studentProfile)->birth_place) }}" required placeholder="Contoh: Jakarta" class="input-control mt-2 @error('birth_place') border-rose-400 @enderror">@error('birth_place')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div><div><label class="text-sm font-semibold text-slate-700">Tanggal Lahir <span class="text-rose-500">*</span></label><input type="date" name="birth_date" value="{{ old('birth_date', optional($studentProfile)->birth_date) }}" required class="input-control mt-2 @error('birth_date') border-rose-400 @enderror">@error('birth_date')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div></div></fieldset>
                <fieldset class="rounded-2xl border border-slate-200 p-4 sm:p-5"><legend class="px-2 text-sm font-bold text-text-navy">C. Data Orang Tua</legend><div class="grid gap-4 sm:grid-cols-2"><div><label class="text-sm font-semibold text-slate-700">Nama Orang Tua <span class="text-rose-500">*</span></label><input name="parent_name" value="{{ old('parent_name', optional($studentProfile)->parent_name) }}" required placeholder="Nama lengkap orang tua" class="input-control mt-2 @error('parent_name') border-rose-400 @enderror">@error('parent_name')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div><div><label class="text-sm font-semibold text-slate-700">Pekerjaan <span class="text-rose-500">*</span></label><input name="parent_job" value="{{ old('parent_job', optional($studentProfile)->parent_job) }}" required placeholder="Contoh: Wiraswasta" class="input-control mt-2 @error('parent_job') border-rose-400 @enderror">@error('parent_job')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div></div></fieldset>
                <fieldset class="rounded-2xl border border-slate-200 p-4 sm:p-5"><legend class="px-2 text-sm font-bold text-text-navy">D. Alamat</legend><label class="text-sm font-semibold text-slate-700">Alamat Lengkap <span class="text-rose-500">*</span></label><textarea name="address" rows="4" required placeholder="Jalan, nomor rumah, RT/RW, kelurahan, kecamatan" class="input-control mt-2 @error('address') border-rose-400 @enderror">{{ old('address', optional($studentProfile)->address) }}</textarea>@error('address')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</fieldset>
                <fieldset class="rounded-2xl border border-slate-200 p-4 sm:p-5"><legend class="px-2 text-sm font-bold text-text-navy">E. Kontak</legend><label class="text-sm font-semibold text-slate-700">Nomor Telepon Orang Tua <span class="text-rose-500">*</span></label><input name="parent_phone" value="{{ old('parent_phone', optional($studentProfile)->parent_phone) }}" required inputmode="tel" placeholder="Contoh: 081234567890" class="input-control mt-2 @error('parent_phone') border-rose-400 @enderror">@error('parent_phone')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</fieldset>
                <button type="submit" class="inline-flex rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-white hover:bg-primary-dark">Simpan Biodata</button>
            </form>
        </section>

        <section id="dokumen" class="card p-5 sm:p-7">
            <div><p class="eyebrow">Tahap 3 dari 5</p><h2 class="mt-1 text-2xl font-bold text-text-navy">Upload Dokumen</h2><p class="mt-2 text-sm text-slate-500">PDF, JPG, atau PNG maksimal 5MB per file.</p></div>
            <form action="{{ route('student.document.upload') }}" method="POST" enctype="multipart/form-data" class="mt-6" @submit="uploading = true">
                @csrf
                <div class="rounded-2xl border-2 border-dashed border-primary/20 bg-primary/[.03] p-5"><div class="flex h-11 w-11 items-center justify-center rounded-xl bg-primary/10 text-xl text-primary">â†‘</div><h3 class="mt-4 font-bold text-slate-800">Upload Dokumen</h3><p class="mt-1 text-xs text-slate-500">Pilih jenis dokumen, lalu pilih file dari perangkat Anda.</p><label class="mt-4 block text-sm font-semibold text-slate-700">Jenis Dokumen <span class="text-rose-500">*</span><select name="file_type" required class="input-control mt-2"><option value="">Pilih dokumen</option>@foreach($documentLabels as $type => $label)<option value="{{ $type }}">{{ $label }}</option>@endforeach</select></label><label class="mt-4 block text-sm font-semibold text-slate-700">File <span class="text-rose-500">*</span><input type="file" name="document" accept="image/jpeg,image/png,application/pdf" required class="mt-2 block w-full rounded-xl border border-slate-200 bg-white p-2 text-sm text-slate-600 file:mr-3 file:rounded-lg file:border-0 file:bg-primary file:px-3 file:py-2 file:text-xs file:font-semibold file:text-white"></label>@error('document')<p class="mt-2 text-xs text-rose-600">{{ $message }}</p>@enderror<button type="submit" :disabled="uploading" class="mt-4 inline-flex rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-white hover:bg-primary-dark disabled:bg-slate-300"><span x-show="!uploading">Upload Dokumen</span><span x-show="uploading" x-cloak>Mengunggah...</span></button><div x-show="uploading" x-cloak class="mt-4"><div class="h-1.5 overflow-hidden rounded-full bg-slate-200"><div class="h-full w-1/3 animate-pulse rounded-full bg-primary"></div></div><p class="mt-1 text-xs text-slate-500">Upload sedang diproses...</p></div></div>
            </form>
            <div class="mt-7"><div class="flex items-center justify-between"><h3 class="font-bold text-text-navy">Daftar dokumen</h3><span class="text-xs text-slate-400">{{ $completedDocuments }}/4 tersedia</span></div><div class="mt-3 space-y-3">
                @foreach($documentLabels as $type => $label)
                    @php $document = $documents->firstWhere('file_type', $type); $docStatus = !$document ? 'Belum Upload' : ($document->notes ? 'Perlu Perbaikan' : ($document->is_verified ? 'Diterima' : 'Menunggu Verifikasi')); $docTone = $docStatus === 'Diterima' ? 'emerald' : ($docStatus === 'Perlu Perbaikan' ? 'orange' : ($docStatus === 'Belum Upload' ? 'slate' : 'amber')); @endphp
                    <div class="rounded-xl border border-slate-200 p-4"><div class="flex items-start gap-3"><span class="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg {{ $docTone === 'emerald' ? 'bg-emerald-50 text-emerald-600' : ($docTone === 'orange' ? 'bg-orange-50 text-orange-600' : ($docTone === 'amber' ? 'bg-amber-50 text-amber-600' : 'bg-slate-100 text-slate-400')) }}">{{ $document ? 'âœ“' : '+' }}</span><div class="min-w-0 flex-1"><div class="flex flex-wrap items-start justify-between gap-2"><div><p class="font-semibold text-slate-800">{{ $label }}</p><p class="mt-1 text-xs text-slate-400">{{ $document ? 'Diunggah ' . $document->created_at->format('d M Y') : 'Belum ada file' }}</p></div><span class="rounded-full px-2.5 py-1 text-[11px] font-semibold {{ $docTone === 'emerald' ? 'bg-emerald-50 text-emerald-700' : ($docTone === 'orange' ? 'bg-orange-50 text-orange-700' : ($docTone === 'amber' ? 'bg-amber-50 text-amber-700' : 'bg-slate-100 text-slate-500')) }}">{{ $docStatus }}</span></div>@if($document)<p class="mt-2 truncate text-xs text-slate-500">{{ basename($document->file_path) }}</p><a href="{{ asset('storage/' . $document->file_path) }}" target="_blank" rel="noopener" class="mt-2 inline-block text-xs font-bold text-primary hover:underline">Lihat dokumen â†—</a>@if($document->notes)<p class="mt-2 text-xs text-orange-700">Catatan: {{ $document->notes }}</p>@endif @endif</div></div></div>
                @endforeach
            </div></div>
        </section>
    </div>

    <section class="card mt-6 p-5 sm:p-7">
        <div><p class="eyebrow">Perjalanan pendaftaran</p><h2 class="mt-1 text-2xl font-bold text-text-navy">Timeline Student</h2><p class="mt-2 text-sm text-slate-500">Tahapan ini mengikuti data pendaftaran dan status verifikasi Anda.</p></div>
        <div class="mt-7 grid gap-5 md:grid-cols-6">
            @foreach($timeline as $index => $step)
                <div class="relative flex gap-3 md:block md:text-center">
                    @if($index < count($timeline) - 1)<div class="absolute left-4 top-9 h-[calc(100%+20px)] w-px {{ $step['done'] ? 'bg-emerald-300' : 'bg-slate-200' }} md:left-[calc(50%+20px)] md:top-4 md:h-px md:w-[calc(100%-40px)]"></div>@endif
                    <div class="relative z-10 mx-0 flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-xs font-bold md:mx-auto {{ ($step['done'] ?? false) ? 'bg-emerald-500 text-white' : (($step['current'] ?? false) ? 'bg-amber-400 text-slate-950 ring-4 ring-amber-100' : 'border-2 border-slate-200 bg-white text-slate-400') }}">{{ ($step['done'] ?? false) ? 'âœ“' : $index + 1 }}</div>
                    <div class="pt-0.5 md:pt-3"><p class="text-sm font-bold {{ ($step['current'] ?? false) ? 'text-amber-700' : 'text-slate-700' }}">{{ $step['label'] }}</p><p class="mt-1 text-xs text-slate-400">{{ ($step['current'] ?? false) ? 'Sedang diproses' : ($step['date'] ?? (($step['done'] ?? false) ? 'Selesai' : 'Belum tercapai')) }}</p></div>
                </div>
            @endforeach
        </div>
    </section>

    <aside class="mt-6 rounded-2xl bg-slate-900 p-6 text-white"><h2 class="font-bold">Panduan singkat</h2><div class="mt-3 grid gap-2 text-sm leading-6 text-slate-300 sm:grid-cols-2"><p>â€¢ Pastikan nama dan NIK sesuai dokumen resmi.</p><p>â€¢ Gunakan foto atau scan yang jelas dan tidak buram.</p><p>â€¢ Setelah upload, tunggu pemeriksaan dari panitia.</p><p>â€¢ Hubungi panitia jika status membutuhkan perbaikan.</p></div></aside>
</div>
@endsection

